name: TF-WorldEdit
version: 2.1.0
main: me.totalfreedom.worldedit.TFWorldEditExtension
api-version: '1.21'
load: STARTUP
softdepend: [WorldEdit, FastAsyncWorldEdit, FastAsyncVoxelSniper, TotalFreedomMod]

description: TotalFreedom WorldEdit Extension - Adds events and anti-grief features for WorldEdit, FAWE, and VoxelSniper
author: TotalFreedom

